#Trigger quand je push sur la branche "main"
on: 
  push:
    branches: main
 
 
jobs: 
  demo: 
    name: demo-ci
    runs-on: ubuntu-latest
    steps: 
      - name: affichage
        run: echo "Hello World"
      - name: Récupération du code
        uses: actions/checkout@v3
      - name: setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
      - run: ./gradlew test  
  build:
    needs: demo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo ${{github.ref_name}}
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/DiceGameForCICD:${{github.ref_name}}

